# Generated by Django 2.0.6 on 2018-06-26 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255, verbose_name='Name of Group')),
                ('user', models.ManyToManyField(related_name='is_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
