# Generated by Django 2.0.6 on 2018-06-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sharegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharegroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShareGroup',
        ),
    ]
